// Package schema generates the JSON Schema (draft 2020-12) document for
// the wire shapes of the Brigade Adapter Protocol v1 (plan 7.3): one
// document with a $defs entry per protocol type, reflected from the Go
// structs of internal/protocol with invopop/jsonschema and then patched
// where reflection cannot see the protocol's rules — the C-23 forbidden
// SendRequest members become `false` property schemas, pointer-typed
// members become nullable, and the 4.4.1 code-point caps become
// maxLength.
//
// This package and its reflection dependency are DEV-ONLY: they are
// linked into cmd/brigade-schema (never shipped) and into tests, never
// into bin/brigade — `make deps-check` asserts the shipped binary's
// module set. Nothing under internal/protocol proper may import this
// package.
//
// The generated document is committed as docs/protocol-v1.schema.json
// (`make schema`) and drift-checked in CI (`make schema-check`), so
// Document must be byte-stable: $defs is assembled in sorted-name order
// and every schema object marshals its members in a deterministic order
// (struct fields in declaration order, Go maps in sorted-key order).
package schema

import (
	"bytes"
	jsonv1 "encoding/json"
	"encoding/json/jsontext"
	json "encoding/json/v2"
	"errors"
	"reflect"
	"sort"
	"strconv"
	"time"

	"github.com/invopop/jsonschema"

	"github.com/appshapes/brigade/internal/protocol"
)

// SchemaID is the canonical location of the committed document.
const SchemaID = "https://raw.githubusercontent.com/appshapes/brigade/master/docs/protocol-v1.schema.json"

// metaSchema is the JSON Schema dialect of the document.
const metaSchema = "https://json-schema.org/draft/2020-12/schema"

// documentDescription states the two things a reader of the schema must
// know: the objects are deliberately loose, and the body cap is measured
// in bytes, which JSON Schema cannot express.
const documentDescription = "Wire shapes of the Brigade adapter protocol, version 1. " +
	"Generated by cmd/brigade-schema; edit the Go types, not this file. " +
	"Objects are deliberately loose (D16): unknown members are ignored by every consumer, " +
	"so no object here sets additionalProperties false, and requiredness is enforced by " +
	"each type's hand-written Validate(), not by this schema. " +
	"The cap on a message body is measured in BYTES of UTF-8 and cannot be expressed here, " +
	"because JSON Schema maxLength counts code points; Validate() enforces the byte cap."

// rootTypes lists every 4.4 wire shape, in the plan's own order. Nested
// shapes (Sender, Limits, ...) are pulled into $defs by reflection.
func rootTypes() []any {
	return []any{
		protocol.Envelope{},            // 4.3
		protocol.ErrorObject{},         // 4.3
		protocol.DescribeResult{},      // 4.4.1
		protocol.SessionRegistration{}, // 4.4.2
		protocol.SessionRecord{},       // 4.4.3
		protocol.HeartbeatRequest{},    // 4.4.4
		protocol.HeartbeatResult{},     // 4.4.4
		protocol.MessageEnvelope{},     // 4.4.5
		protocol.SendRequest{},         // 4.4.6
		protocol.SendResponse{},        // 4.4.7
		protocol.AckRequest{},          // 4.4.8
		protocol.AckResult{},           // 4.4.8
		protocol.WatchReady{},          // 4.4.9
		protocol.WatchMessage{},        // 4.4.9
		protocol.WatchStatus{},         // 4.4.9
		protocol.WatchAcked{},          // 4.4.9
		protocol.WatchHeartbeatOK{},    // 4.4.9
		protocol.WatchError{},          // 4.4.9
		protocol.WatchCommand{},        // 4.4.9
		protocol.TeamCreateRequest{},   // 4.4.10
		protocol.TeamCreateResult{},    // 4.4.10
		protocol.TeamJoinRequest{},     // 4.4.10
		protocol.TeamJoinResult{},      // 4.4.10
		protocol.TeamLeaveResult{},     // 4.4.10
	}
}

// forbiddenSendMembers are the C-23 members of SendRequest (4.4.6): the
// adapter stamps them from its own authority, so each is declared as the
// `false` schema — any presence, with any value including null, fails.
var forbiddenSendMembers = []string{
	"sender", "principal_ref", "human_label", "team_ref", "created_at", "hop_count",
}

// document is the top-level schema object. Field order here is member
// order in the output.
type document struct {
	Schema      string         `json:"$schema"`
	ID          string         `json:"$id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Defs        jsontext.Value `json:"$defs"`
}

// Document returns the complete schema document, indented with two
// spaces and terminated by a newline. The bytes are stable across calls,
// runs and machines for a given version of this package and its
// dependencies; TestDocumentStable and `make schema-check` pin that.
func Document() ([]byte, error) {
	defs, err := reflectDefinitions()
	if err != nil {
		return nil, err
	}
	if err := patchDefinitions(defs); err != nil {
		return nil, err
	}
	rawDefs, err := marshalDefinitions(defs)
	if err != nil {
		return nil, err
	}
	doc := document{
		Schema:      metaSchema,
		ID:          SchemaID,
		Title:       "Brigade Adapter Protocol v1 (BAP/1)",
		Description: documentDescription,
		Defs:        rawDefs,
	}
	b, err := json.Marshal(doc, jsontext.WithIndent("  "))
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// reflectDefinitions reflects every root type and merges the resulting
// definitions into one map. A name that reflects to two different
// schemas is an error, not a silent overwrite.
func reflectDefinitions() (jsonschema.Definitions, error) {
	r := &jsonschema.Reflector{
		// One hand-built $id for the whole document; no per-type IDs.
		Anonymous: true,
		// The objects are LOOSE (D16): additionalProperties is never false.
		AllowAdditionalProperties: true,
		// Required comes only from explicit jsonschema tags. The wire
		// structs carry none, so no member is required here; Validate()
		// is the normative check (plan 7.3).
		RequiredFromJSONSchemaTags: true,
		// jsontext.Value would otherwise reflect as a base64 string
		// definition named "Value". Every jsontext.Value member is
		// patched to its real shape below; `true` (any JSON value) is
		// the safe default for one that is not.
		Mapper: func(t reflect.Type) *jsonschema.Schema {
			if t == reflect.TypeOf(jsontext.Value(nil)) {
				return &jsonschema.Schema{}
			}
			return nil
		},
	}
	merged := jsonschema.Definitions{}
	for _, root := range rootTypes() {
		s := r.Reflect(root)
		for name, def := range s.Definitions {
			if have, ok := merged[name]; ok {
				a, err := jsonv1.Marshal(have)
				if err != nil {
					return nil, err
				}
				b, err := jsonv1.Marshal(def)
				if err != nil {
					return nil, err
				}
				if !bytes.Equal(a, b) {
					return nil, errors.New("schema: definition " + name + " reflected to two different schemas")
				}
				continue
			}
			merged[name] = def
		}
	}
	for _, root := range rootTypes() {
		name := reflect.TypeOf(root).Name()
		if _, ok := merged[name]; !ok {
			return nil, errors.New("schema: root type " + name + " produced no definition")
		}
	}
	return merged, nil
}

// patchDefinitions applies everything reflection cannot know, in a fixed
// order. Every patch fails loudly when its definition or property is
// missing, so a renamed wire member cannot silently leave a stale patch
// behind.
func patchDefinitions(defs jsonschema.Definitions) error {
	// 4.4.1 code-point caps as maxLength (JSON Schema maxLength counts
	// code points, exactly what capRunes counts).
	for _, c := range []struct {
		def, prop string
		limit     int
	}{
		{"Sender", "session_name", protocol.MaxSessionNameCodepoints},
		{"Sender", "human_label", protocol.MaxHumanLabelChars},
		{"MessageEnvelope", "summary", protocol.MaxSummaryChars},
		{"SendRequest", "summary", protocol.MaxSummaryChars},
		{"SendRequest", "idempotency_key", protocol.MaxIdempotencyKeyChars},
		{"SessionRegistration", "session_name", protocol.MaxSessionNameCodepoints},
		{"SessionRegistration", "session_description", protocol.MaxDescriptionChars},
		{"SessionRegistration", "workspace_label", protocol.MaxHumanLabelChars},
		{"SessionRecord", "session_name", protocol.MaxSessionNameCodepoints},
		{"SessionRecord", "session_description", protocol.MaxDescriptionChars},
		{"SessionRecord", "human_label", protocol.MaxHumanLabelChars},
		{"SessionRecord", "workspace_label", protocol.MaxHumanLabelChars},
		{"HeartbeatRequest", "session_name", protocol.MaxSessionNameCodepoints},
		{"HeartbeatRequest", "session_description", protocol.MaxDescriptionChars},
		{"WatchCommand", "session_name", protocol.MaxSessionNameCodepoints},
		{"TeamCreateRequest", "team_name", protocol.MaxSessionNameCodepoints},
		{"TeamCreateRequest", "human_label", protocol.MaxHumanLabelChars},
		{"TeamCreateResult", "team_name", protocol.MaxSessionNameCodepoints},
		{"TeamJoinRequest", "human_label", protocol.MaxHumanLabelChars},
		{"TeamJoinResult", "team_name", protocol.MaxSessionNameCodepoints},
		{"ProfileInfo", "human_label", protocol.MaxHumanLabelChars},
	} {
		limit := uint64(c.limit) // #nosec G115 -- protocol constants, all small positives
		if err := patchProp(defs, c.def, c.prop, func(s *jsonschema.Schema) *jsonschema.Schema {
			s.MaxLength = &limit
			return s
		}); err != nil {
			return err
		}
	}

	// Numeric protocol bounds (4.4.1, 4.5.12).
	for _, c := range []struct {
		def, prop string
		min, max  int
	}{
		{"SessionRegistration", "lease_seconds", protocol.LeaseMinSeconds, protocol.LeaseMaxSeconds},
		{"HeartbeatRequest", "lease_seconds", protocol.LeaseMinSeconds, protocol.LeaseMaxSeconds},
		{"WatchCommand", "lease_seconds", protocol.LeaseMinSeconds, protocol.LeaseMaxSeconds},
		{"MessageEnvelope", "hop_count", 0, protocol.MaxHopCount},
		{"SendResponse", "hop_count", 0, protocol.MaxHopCount},
		{"ErrorObject", "retry_after_ms", 0, -1}, // no upper bound
	} {
		minimum := jsonv1.Number(strconv.Itoa(c.min))
		var maximum jsonv1.Number
		if c.max >= 0 {
			maximum = jsonv1.Number(strconv.Itoa(c.max))
		}
		if err := patchProp(defs, c.def, c.prop, func(s *jsonschema.Schema) *jsonschema.Schema {
			s.Minimum = minimum
			s.Maximum = maximum
			return s
		}); err != nil {
			return err
		}
	}

	// The body byte cap, which maxLength cannot carry (it counts code
	// points): stated in the description, enforced by Validate().
	bodyDescription := "UTF-8 text of at most " + strconv.Itoa(protocol.MaxBodyBytes) +
		" BYTES. The cap is measured in bytes and cannot be expressed as maxLength, " +
		"which counts code points; Validate() enforces it."
	for _, def := range []string{"MessageEnvelope", "SendRequest"} {
		if err := patchProp(defs, def, "body", func(s *jsonschema.Schema) *jsonschema.Schema {
			s.Description = bodyDescription
			return s
		}); err != nil {
			return err
		}
	}

	// The two members carried as jsontext.Value that are real shapes.
	if err := patchProp(defs, "Envelope", "result", func(*jsonschema.Schema) *jsonschema.Schema {
		return &jsonschema.Schema{
			Type:        "object",
			Description: "Command-specific result object (4.2); present exactly when ok is true.",
		}
	}); err != nil {
		return err
	}
	if err := patchProp(defs, "TeamJoinRequest", "backend", func(*jsonschema.Schema) *jsonschema.Schema {
		return &jsonschema.Schema{
			Type: "object",
			Description: "Adapter-specific backend configuration (Supabase: url, publishable_key); " +
				"accepted only when the profile has no backend configured (4.4.10).",
		}
	}); err != nil {
		return err
	}

	// C-23: each forbidden SendRequest member is the `false` schema, so
	// its presence with ANY value, null included, fails validation.
	for _, member := range forbiddenSendMembers {
		if err := patchProp(defs, "SendRequest", member, func(*jsonschema.Schema) *jsonschema.Schema {
			return jsonschema.FalseSchema
		}); err != nil {
			return err
		}
	}
	if err := patchDef(defs, "SendRequest", func(s *jsonschema.Schema) {
		s.Description = "The message send request (4.4.6). The one shape where loose parsing has a " +
			"named exception (C-23): sender, principal_ref, human_label, team_ref, created_at and " +
			"hop_count are stamped by the adapter from its own authority, so each is declared as " +
			"the false schema here and its presence with any value, null included, is invalid."
	}); err != nil {
		return err
	}

	// Pointer-typed members accept an explicit JSON null (plan 7.3:
	// pointers where null and absent must differ). The one exception is
	// error.retryable, which 4.3 makes REQUIRED and whose null
	// Validate() rejects; its pointer exists to detect absence, not to
	// permit null.
	for _, p := range nullableProps() {
		if err := patchProp(defs, p.def, p.prop, func(s *jsonschema.Schema) *jsonschema.Schema {
			return &jsonschema.Schema{AnyOf: []*jsonschema.Schema{s, {Type: "null"}}}
		}); err != nil {
			return err
		}
	}
	return nil
}

// notNullable lists pointer-typed members whose explicit null is invalid
// on the wire (rejected by Validate), keyed def then prop.
var notNullable = map[string]map[string]bool{
	"ErrorObject": {"retryable": true},
}

// defProp names one property of one definition.
type defProp struct{ def, prop string }

// nullableProps walks the Go wire types and returns every pointer-typed
// exported member (minus the notNullable exceptions), sorted, so the
// nullability patches track the structs as other files change them.
func nullableProps() []defProp {
	found := map[defProp]bool{}
	seen := map[reflect.Type]bool{}
	var walk func(t reflect.Type)
	walk = func(t reflect.Type) {
		for t.Kind() == reflect.Pointer || t.Kind() == reflect.Slice ||
			t.Kind() == reflect.Array || t.Kind() == reflect.Map {
			t = t.Elem()
		}
		if t.Kind() != reflect.Struct || t == reflect.TypeOf(time.Time{}) || seen[t] {
			return
		}
		seen[t] = true
		for i := range t.NumField() {
			f := t.Field(i)
			if f.PkgPath != "" { // unexported
				continue
			}
			name := jsonMemberName(f)
			if name == "" {
				continue
			}
			if f.Type.Kind() == reflect.Pointer && !notNullable[t.Name()][name] {
				found[defProp{t.Name(), name}] = true
			}
			walk(f.Type)
		}
	}
	for _, root := range rootTypes() {
		walk(reflect.TypeOf(root))
	}
	props := make([]defProp, 0, len(found))
	for p := range found {
		props = append(props, p)
	}
	sort.Slice(props, func(i, j int) bool {
		if props[i].def != props[j].def {
			return props[i].def < props[j].def
		}
		return props[i].prop < props[j].prop
	})
	return props
}

// jsonMemberName returns the wire name of a struct field, or "" for one
// that is not a JSON member.
func jsonMemberName(f reflect.StructField) string {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return ""
	}
	for i := range len(tag) {
		if tag[i] == ',' {
			tag = tag[:i]
			break
		}
	}
	if tag == "" {
		return f.Name
	}
	return tag
}

// patchProp rewrites one property schema of one definition and fails
// when either does not exist.
func patchProp(defs jsonschema.Definitions, def, prop string, f func(*jsonschema.Schema) *jsonschema.Schema) error {
	d, ok := defs[def]
	if !ok {
		return errors.New("schema: patch names unknown definition " + def)
	}
	if d.Properties == nil {
		return errors.New("schema: definition " + def + " has no properties to patch")
	}
	s, ok := d.Properties.Get(prop)
	if !ok {
		return errors.New("schema: patch names unknown property " + def + "." + prop)
	}
	d.Properties.Set(prop, f(s))
	return nil
}

// patchDef rewrites one definition in place and fails when it does not
// exist.
func patchDef(defs jsonschema.Definitions, def string, f func(*jsonschema.Schema)) error {
	d, ok := defs[def]
	if !ok {
		return errors.New("schema: patch names unknown definition " + def)
	}
	f(d)
	return nil
}

// marshalDefinitions renders $defs with its member names sorted, so the
// output does not depend on Go map iteration order.
func marshalDefinitions(defs jsonschema.Definitions) (jsontext.Value, error) {
	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)
	var buf bytes.Buffer
	buf.WriteByte('{')
	for i, name := range names {
		if i > 0 {
			buf.WriteByte(',')
		}
		key, err := jsonv1.Marshal(name)
		if err != nil {
			return nil, err
		}
		buf.Write(key)
		buf.WriteByte(':')
		val, err := jsonv1.Marshal(defs[name])
		if err != nil {
			return nil, err
		}
		buf.Write(val)
	}
	buf.WriteByte('}')
	return jsontext.Value(buf.Bytes()), nil
}
