// Command brigade-schema writes the Brigade Adapter Protocol JSON Schema
// document to stdout. `make schema` redirects it into
// docs/protocol-v1.schema.json and `make schema-check` diffs the two, so
// its output must be byte-identical between runs and between machines.
//
// P1-1 state: internal/protocol does not exist yet, so the document is the
// envelope with an empty `$defs`. P1-2 replaces Document with a reflection
// of the wire structs (invopop/jsonschema, plan 7.3); the dependency is
// deliberately not taken here, because reflecting nothing buys nothing and
// go.mod would carry a requirement no code uses.
package main

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"io"
	"os"
)

// schemaID is the canonical location of the committed document.
const schemaID = "https://raw.githubusercontent.com/appshapes/brigade/master/docs/protocol-v1.schema.json"

// document is the top-level schema. The field order of this struct is the
// member order of the output, which is what makes the bytes stable: no map
// is ever ranged over to produce a line.
type document struct {
	Schema      string `json:"$schema"`
	ID          string `json:"$id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	// Defs holds one subschema per wire type. It is an ordered document
	// value rather than a Go map so that P1-2 cannot introduce map-ordering
	// instability into a file CI diffs.
	Defs jsontext.Value `json:"$defs"`
}

// Document returns the schema document bytes, indented with two spaces and
// terminated by a newline.
func Document() ([]byte, error) {
	doc := document{
		Schema: "https://json-schema.org/draft/2020-12/schema",
		ID:     schemaID,
		Title:  "Brigade Adapter Protocol v1 (BAP/1)",
		Description: "Wire shapes of the Brigade adapter protocol, version 1. " +
			"Generated by cmd/brigade-schema; edit the Go types, not this file. " +
			"Byte caps on message bodies are measured in bytes and cannot be expressed here, " +
			"because JSON Schema maxLength counts code points; the adapter's Validate() enforces them.",
		// $defs is empty until P1-2 defines the wire types.
		Defs: jsontext.Value("{}"),
	}
	b, err := json.Marshal(doc, jsontext.WithIndent("  "))
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func main() { os.Exit(run(os.Stdout, os.Stderr)) }

func run(stdout, stderr io.Writer) int {
	b, err := Document()
	if err != nil {
		_, _ = io.WriteString(stderr, "brigade-schema failed (internal): "+err.Error()+"\n")
		return 1
	}
	if _, err := stdout.Write(b); err != nil {
		_, _ = io.WriteString(stderr, "brigade-schema failed (internal): "+err.Error()+"\n")
		return 1
	}
	return 0
}
